Repository diasurgical/devilutionX, pull requests merged in 2021-06, with the labels that each got.

#2100 crypt fix
  Source/drlg_l1.cpp
Labels: fix

#2109 fix loading screens:
  Source/interfac.cpp
Labels: fix

#2121 update asio
  3rdParty/asio/CMakeLists.txt
Labels: fix

#2122 fix magic rock highlight
  Source/scrollrt.cpp
Labels: fix

#2120 fix wrong sound/message
  Source/missiles.cpp
  Source/multi.cpp
Labels: fix

#2129 fix thaumaturgic
  Source/objects.cpp
Labels: fix, vanilla

#2152 Ensure AnimationInfo is reset when a game is loaded
  Source/loadsave.cpp
Labels: fix

#2165 Set up CI for Android builds
  .circleci/config.yml
  android-project/app/build.gradle
Labels: buid system

#808 Reword potion effect descriptions for consistency
  Source/items.cpp
Labels: proposal, vanilla
