Repository diasurgical/devilutionX, pull requests merged in 2021-04, with the labels that each got.

#1349 fix gold spinner
  Source/control.cpp
Labels: fix

#690 Add support for network play over ZeroTier
  3rdParty/libzt/CMakeLists.txt
  CMake/mingwcc.cmake
  CMake/mingwcc64.cmake
  CMakeLists.txt
  SourceX/DiabloUI/selconn.cpp
  SourceX/dvlnet/abstract_net.cpp
  SourceX/dvlnet/abstract_net.h
  SourceX/dvlnet/base.cpp
  SourceX/dvlnet/base.h
  SourceX/dvlnet/base_protocol.cpp
  SourceX/dvlnet/base_protocol.h
  SourceX/dvlnet/cdwrap.h
  SourceX/dvlnet/frame_queue.h
  SourceX/dvlnet/loopback.cpp
  SourceX/dvlnet/loopback.h
  SourceX/dvlnet/packet.cpp
  SourceX/dvlnet/packet.h
  SourceX/dvlnet/protocol_zt.cpp
  SourceX/dvlnet/protocol_zt.h
  SourceX/dvlnet/tcp_client.cpp
  SourceX/dvlnet/tcp_client.h
  SourceX/dvlnet/tcp_server.h
  SourceX/dvlnet/udp_p2p.cpp
  SourceX/dvlnet/udp_p2p.h
  SourceX/dvlnet/zerotier_lwip.cpp
  SourceX/dvlnet/zerotier_lwip.h
  SourceX/dvlnet/zerotier_native.cpp
  SourceX/dvlnet/zerotier_native.h
  SourceX/storm/storm_dvlnet.h
  SourceX/storm/storm_net.cpp
  enums.h
Labels: enhancement

#1427 proper heroitems size
  Source/loadsave.cpp
Labels: fix

#1479 fix vanilla premium items going over 140k
  Source/items.cpp
Labels: fix

#1495 fix gharbad and vision
  Source/lighting.cpp
  Source/player.cpp
Labels: fix

#1529 fix loading golem
  Source/loadsave.cpp
Labels: fix

#1540 fix double zhar aggro message
  Source/objects.cpp
Labels: fix, vanilla

#1543 Invcleanup part 2
  Source/inv.cpp
  Source/inv.h
  Source/items.cpp
  Source/items.h
  Source/scrollrt.cpp
Labels: enhancement

#1553 🐛 Ensure picked up items on the ground are removed
  Source/inv.cpp
Labels: fix

#1558 make unique items display gold in stores
  Source/stores.cpp
Labels: enhancement

#1569 fix typo in Shimmering Shrine
  Source/error.cpp
Labels: fix, vanilla

#1572 remove unique item line from shops
  Source/stores.cpp
Labels: enhancement

#1590 Stops golems from fighting each other
  Source/monster.cpp
Labels: fix, vanilla

#1635 fix secluded crash
  Source/objects.cpp
Labels: fix

#1660 Fix for "Distant sound sources aren't panned correctly"
  Source/utils/soundsample.cpp
Labels: fix

#1664 fix monk
  Source/player.cpp
Labels: fix

#1678 fix queuing operating object when clicking during attack
  Source/player.cpp
Labels: fix, vanilla
