Repository diasurgical/devilutionX, pull requests merged in 2021-09, with the labels that each got.

#2769 fix currlevel in map command
  Source/debug.cpp
Labels: fix

#2766 fix quest unique monster level
  Source/monster.cpp
Labels: vanilla, fix

#2811 :bug: Fix teleport not working in all locations
  Source/missiles.cpp
Labels: vanilla, fix

#2763 fix loot - use proper monster level for generating items
  Source/items.cpp
Labels: enhancement, vanilla, fix, critical

#2822 fix golems on maps with set pieces
  Source/monster.cpp
Labels: vanilla, fix

#2834 fix golem spawning on top of player
  Source/missiles.cpp
Labels: vanilla, fix

#2758 debug X toggle
  Source/debug.cpp
  Source/debug.h
  Source/diablo.cpp
Labels: enhancement

#2847 tiledata debug command
  Source/debug.cpp
  Source/debug.h
  Source/scrollrt.cpp
Labels: enhancement

#2849 fix chat line wrapping
  Source/engine/render/text_render.cpp
Labels: fix

#2856 🐛 Prevent frame-perfect manipulation of spell being cast
  Source/msg.cpp
  Source/msg.h
  Source/player.cpp
Labels: fix

#2879 fix stuck chargers
  Source/diablo.cpp
Labels: vanilla, fix

#2878 fix saves bricked by spawn command
  Source/monster.cpp
Labels: fix

#2884 fix destroying renderer
  Source/dx.cpp
Labels: fix

#2896 fix quest panel
  Source/quests.cpp
Labels: fix

#2922 fix wrong armor display in multiplayer
  Source/inv.cpp
Labels: fix

#2923 proper fix for multiplayer item sync
  Source/inv.cpp
Labels: fix

#2928 Fix unique typos
  Source/itemdat.cpp
  Translations/bg.po
  Translations/da.po
  Translations/de.po
  Translations/devilutionx.pot
  Translations/es.po
  Translations/fr.po
  Translations/hr.po
  Translations/it.po
  Translations/ko_KR.po
  Translations/pl.po
  Translations/pt_BR.po
  Translations/ru.po
  Translations/sv.po
  Translations/zh_CN.po
  Translations/zh_TW.po
Labels: vanilla, fix

#2992 fix light stealing in multi
  Source/msg.cpp
  Source/player.cpp
Labels: fix
