Repository diasurgical/devilutionX, pull requests merged in 2021-02, with the labels that each got.

#1002 update damage after leveling up
  Source/player.cpp
Labels: enhancement

#1011 Fix portals appearing on wrong levels
  Source/portal.cpp
Labels: bug, fix, vanilla

#1014 unify checks for single and multiplayer
  Source/appfat.cpp
  Source/automap.cpp
  Source/control.cpp
  Source/diablo.cpp
  Source/drlg_l1.cpp
  Source/drlg_l2.cpp
  Source/drlg_l4.cpp
  Source/dthread.cpp
  Source/effects.cpp
  Source/gamemenu.cpp
  Source/interfac.cpp
  Source/inv.cpp
  Source/items.cpp
  Source/mainmenu.cpp
  Source/missiles.cpp
  Source/monster.cpp
  Source/msg.cpp
  Source/multi.cpp
  Source/multi.h
  Source/nthread.cpp
  Source/objects.cpp
  Source/pack.cpp
  Source/pfile.cpp
  Source/player.cpp
  Source/quests.cpp
  Source/scrollrt.cpp
  Source/stores.cpp
  Source/town.cpp
  Source/towners.cpp
  Source/trigs.cpp
  SourceT/diablo_test.cpp
  SourceX/DiabloUI/selhero.cpp
  SourceX/controls/plrctrls.cpp
Labels: enhancement

#834 prevent mana gain from books when nomana flag is set
  Source/items.cpp
Labels: bug, vanilla

#1027 numpad potions + chat
  SourceS/miniwin/misc.h
  SourceX/miniwin/misc_msg.cpp
Labels: fix
