Repository diasurgical/devilutionX, pull requests merged in 2021-03, with the labels that each got.

#1057 fix text scroll speed
  SourceX/soundsample.cpp
Labels: fix

#861 Autoequip all items on pickup
  Source/inv.cpp
Labels: enhancement

#852 Allow shift+click moving to inventory
  Source/diablo.cpp
  Source/help.cpp
  Source/inv.cpp
  Source/inv.h
Labels: enhancement

#806 Expose monster type on monster info
  Source/diablo.cpp
  Source/diablo.h
  Source/monster.cpp
  SourceX/qol.cpp
Labels: enhancement, proposal
