Repository diasurgical/devilutionX, pull requests merged in 2022-04, with the labels that each got.

#3938 Update Croatian translation
  Translations/hr.po
Labels: translation

#4047 fix armor pierce on uniques and display affix values
  Source/itemdat.cpp
  Source/items.cpp
Labels: enhancement, fix

#4490 Clear held item when putting in an empty belt slot
  Source/inv.cpp
Labels: fix

#4525 HP bar tweaks and fixes
  Source/monster.cpp
  Source/qol/monhealthbar.cpp
Labels: enhancement, fix

#4528 fix displacement on death
  Source/scrollrt.cpp
Labels: fix
