Repository diasurgical/devilutionX, pull requests merged in 2022-02, with the labels that each got.

#4056 TRN rewrite + bugfix
  Source/CMakeLists.txt
  Source/control.cpp
  Source/dead.cpp
  Source/engine/render/cel_render.cpp
  Source/engine/render/cl2_render.cpp
  Source/engine/render/cl2_render.hpp
  Source/engine/render/common_impl.h
  Source/engine/trn.cpp
  Source/engine/trn.hpp
  Source/lighting.h
  Source/missiles.cpp
  Source/monster.cpp
  Source/monster.h
  Source/scrollrt.cpp
Labels: enhancement, fix

#4079 add a check for trap missiles for TRNs
  Source/missiles.cpp
Labels: fix

#4087 Fix format strings in PrintDebugMonster()
  Source/debug.cpp
Labels: fix

#4094 fix spawning unique monsters
  Source/debug.cpp
  Source/effects.cpp
  Source/monster.cpp
  Source/monster.h
Labels: enhancement
